# Generated by Django 4.0.6 on 2022-07-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='sl name')),
                ('nam2', models.CharField(max_length=40, verbose_name='sl name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='In image')),
            ],
            options={
                'verbose_name': 'IndexSl',
                'verbose_name_plural': 'IndexSls',
            },
        ),
    ]
