# Generated by Django 4.0.6 on 2022-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_indexbg_indexprog_indexprog2_indexwelc'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexprog',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='img prog'),
        ),
        migrations.AlterField(
            model_name='indexwelc',
            name='name2',
            field=models.CharField(max_length=80, null=True, verbose_name='welc name2'),
        ),
    ]
