# Generated by Django 4.0.6 on 2022-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_indexprog_img_alter_indexwelc_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='blog name')),
                ('name2', models.CharField(max_length=90, verbose_name='blog name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='img bolo')),
            ],
            options={
                'verbose_name': 'IndexBlog',
                'verbose_name_plural': 'IndexBlogs',
            },
        ),
        migrations.CreateModel(
            name='IndexChoos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='ch name')),
                ('name2', models.TextField(verbose_name='ch text')),
                ('img', models.ImageField(upload_to='media', verbose_name='img name')),
            ],
            options={
                'verbose_name': 'IndexChoos',
                'verbose_name_plural': 'IndexChooss',
            },
        ),
        migrations.CreateModel(
            name='IndexPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='plan name')),
                ('name2', models.TextField(verbose_name='plan text')),
                ('img', models.ImageField(upload_to='media', verbose_name='plan2 img')),
            ],
            options={
                'verbose_name': 'IndexPlan',
                'verbose_name_plural': 'IndexPlans',
            },
        ),
        migrations.CreateModel(
            name='IndexPlan2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='plan2 name')),
                ('price', models.IntegerField(verbose_name='plan2 price')),
                ('name2', models.CharField(max_length=80, verbose_name='plan2 name')),
                ('name3', models.CharField(max_length=80, verbose_name='plan2 name')),
                ('name4', models.CharField(max_length=80, verbose_name='plan2 name')),
                ('name5', models.CharField(max_length=80, verbose_name='plan2 name')),
            ],
            options={
                'verbose_name': 'IndexPlan2M',
                'verbose_name_plural': 'IndexPlan2Ms',
            },
        ),
        migrations.CreateModel(
            name='IndexVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Video name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Video img')),
            ],
            options={
                'verbose_name': 'IndexVideo',
                'verbose_name_plural': 'IndexVideos',
            },
        ),
        migrations.AlterField(
            model_name='indexprog',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='prog img'),
        ),
    ]
