# Generated by Django 4.0.6 on 2022-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_indexlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='bg name')),
                ('name2', models.TextField(verbose_name='bg text')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'AboutBg',
                'verbose_name_plural': 'AboutBgs',
            },
        ),
        migrations.CreateModel(
            name='AboutQu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
                ('text', models.TextField(verbose_name='taxt')),
                ('numb', models.CharField(max_length=90, verbose_name='numb4')),
            ],
            options={
                'verbose_name': 'AboutQu',
                'verbose_name_plural': 'AboutQus',
            },
        ),
        migrations.CreateModel(
            name='AboutSl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name1')),
                ('name2', models.CharField(max_length=90, verbose_name='name2')),
                ('text', models.TextField(verbose_name='text')),
                ('img', models.ImageField(upload_to='media', verbose_name='img1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='img2')),
            ],
            options={
                'verbose_name': 'AboutSl',
                'verbose_name_plural': 'AboutSls',
            },
        ),
        migrations.CreateModel(
            name='AboutTr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name trainer')),
                ('img', models.ImageField(upload_to='media', verbose_name='img trainer')),
            ],
            options={
                'verbose_name': 'AboutTr',
                'verbose_name_plural': 'AboutTrs',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name ')),
                ('name2', models.TextField(verbose_name='Us text')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUss',
            },
        ),
    ]
