# Generated by Django 4.0.6 on 2022-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutbg_aboutqu_aboutsl_abouttr_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutqu',
            name='numb2',
            field=models.CharField(max_length=90, null=True, verbose_name='numb2'),
        ),
        migrations.AddField(
            model_name='aboutqu',
            name='numb3',
            field=models.CharField(max_length=90, null=True, verbose_name='numb3'),
        ),
        migrations.AddField(
            model_name='aboutqu',
            name='numb4',
            field=models.CharField(max_length=90, null=True, verbose_name='numb4'),
        ),
        migrations.AlterField(
            model_name='aboutqu',
            name='numb',
            field=models.CharField(max_length=90, verbose_name='numb'),
        ),
    ]
