# Generated by Django 4.0.6 on 2022-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutsl2_remove_aboutsl_img2_aboutus_name3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutlogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Aboutlogo',
                'verbose_name_plural': 'Aboutlogos',
            },
        ),
    ]
