# Generated by Django 4.0.6 on 2022-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScOur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='class')),
                ('text', models.TextField(verbose_name='text')),
                ('img', models.ImageField(upload_to='media', verbose_name='img class')),
            ],
            options={
                'verbose_name': 'ScOur',
                'verbose_name_plural': 'ScOurs',
            },
        ),
    ]
