# Generated by Django 4.0.6 on 2022-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_blog1_blog2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text 1')),
                ('text2', models.TextField(verbose_name='text 2')),
                ('img', models.ImageField(upload_to='media', verbose_name='img 1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='img 2')),
                ('img3', models.ImageField(upload_to='media', verbose_name='img 3')),
                ('img4', models.ImageField(upload_to='media', verbose_name='img 4')),
            ],
            options={
                'verbose_name': 'BlogDet',
                'verbose_name_plural': 'BlogDets',
            },
        ),
        migrations.CreateModel(
            name='BlogDet2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Blog name')),
                ('text', models.TextField(verbose_name='text1')),
                ('text2', models.TextField(verbose_name='text2')),
                ('text3', models.TextField(verbose_name='text3')),
                ('stname', models.CharField(max_length=50, verbose_name='str name1')),
                ('strnam2', models.CharField(max_length=50, verbose_name='str author name')),
            ],
            options={
                'verbose_name': 'BlogDet2',
                'verbose_name_plural': 'BlogDet2s',
            },
        ),
        migrations.CreateModel(
            name='BlogDeth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name1')),
                ('name2', models.CharField(max_length=30, verbose_name='name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='img ')),
            ],
            options={
                'verbose_name': 'BlogDeth',
                'verbose_name_plural': 'BlogDeths',
            },
        ),
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='video name')),
                ('imga', models.ImageField(upload_to='media', verbose_name='videp img')),
            ],
            options={
                'verbose_name': 'BlogVideo',
                'verbose_name_plural': 'BlogVideos',
            },
        ),
    ]
