# Generated by Django 4.0.6 on 2022-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_blogdet_blogdet2_blogdeth_blogvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDet3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name1')),
                ('name2', models.CharField(max_length=80, verbose_name='name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'BlogDet3',
                'verbose_name_plural': 'BlogDet3s',
            },
        ),
        migrations.CreateModel(
            name='BlogDetN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name1')),
                ('name2', models.CharField(max_length=80, verbose_name='name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'BlogDetN',
                'verbose_name_plural': 'BlogDetNs',
            },
        ),
        migrations.AddField(
            model_name='blogdet2',
            name='strnam3',
            field=models.CharField(max_length=120, null=True, verbose_name='str  name3'),
        ),
        migrations.AlterField(
            model_name='blogdet2',
            name='stname',
            field=models.CharField(max_length=120, null=True, verbose_name='str name1'),
        ),
        migrations.AlterField(
            model_name='blogdet2',
            name='strnam2',
            field=models.CharField(max_length=120, null=True, verbose_name='str author name'),
        ),
    ]
