# Generated by Django 4.0.6 on 2022-08-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_blogdet3_blogdetn_blogdet2_strnam3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name categgory')),
            ],
            options={
                'verbose_name': 'GalCat',
                'verbose_name_plural': 'GalCats',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
                ('galcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gal', to='main.galcat')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallerys',
            },
        ),
    ]
