# Generated by Django 4.0.6 on 2022-08-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_galcat_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=90, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name2',
            field=models.CharField(max_length=90, null=True, verbose_name='name2 '),
        ),
    ]
