# Generated by Django 4.0.6 on 2022-08-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_blogvideo_imga_blogvideo_img_blogvideo_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo4',
            name='name',
            field=models.CharField(max_length=90, null=True, verbose_name='name logo1'),
        ),
        migrations.AddField(
            model_name='logo4',
            name='name2',
            field=models.CharField(max_length=90, null=True, verbose_name='name logo2'),
        ),
        migrations.AddField(
            model_name='logo4',
            name='name3',
            field=models.CharField(max_length=90, null=True, verbose_name='name logo3'),
        ),
    ]
