from django.contrib import admin
from .models import *


# Register your models here.

admin.site.register(IndexLogo)
admin.site.register(IndexSl)
admin.site.register(IndexBg)
admin.site.register(IndexWelc)
admin.site.register(IndexProg)
admin.site.register(IndexProg2)
admin.site.register(IndexPlan)
admin.site.register(IndexPlan2M)
admin.site.register(IndexBlog)
admin.site.register(IndexVideo)
admin.site.register(IndexChoos)
admin.site.register(AboutBg)
admin.site.register(AboutTr)
admin.site.register(AboutSl)
admin.site.register(AboutUs)
admin.site.register(AboutQu)
admin.site.register(AboutSl2)
admin.site.register(Aboutlogo)
admin.site.register(ScOur)
admin.site.register(Blog1)
admin.site.register(Blog2)
admin.site.register(BlogDet)
admin.site.register(BlogDet2)
admin.site.register(BlogDeth)
admin.site.register(BlogVideo)
admin.site.register(BlogDet3)
admin.site.register(BlogDetN)
admin.site.register(GalCat)
admin.site.register(Gallery)
admin.site.register(Logo)
admin.site.register(Logo2)
admin.site.register(Logo3)
admin.site.register(Logo4)